config/routes.rb
Rails.application.routes.draw do

  root 'demo#index'

  get 'admin', :to => 'access#menu'   #if they are logged in, they'll get the menu page they wanted, else they get the login form.
  get 'access/menu'
  get 'access/login'    #can treat as resourceful route or simple controller

  post 'access/attempt_login'
  get 'access/logout'

  resources :posts
  resources :subjects do
    member do
      get :delete
    end
  end

  resources :pages do
    member do
      get :delete
    end
  end

  resources :sections do
    member do
      get :delete
    end
  end

  # get 'pages/index'
  # get 'pages/show'
  # get 'pages/new'
  # get 'pages/edit'
  # get 'pages/delete'
  
  # get 'subjects/index'
  # get 'subjects/show'
  # get 'subjects/new'
  # get 'subjects/edit'
  # get 'subjects/delete'
  # get 'self_contr/home'

  #root "demo#index"
  get 'demo/index'        #simple route
  #get 'demo/hello'  # get ':controller(/:action(/:id))'  #default route
  #get 'demo/about'
  #get 'demo/contact'
end

app/controllers/access_controller.rb
class AccessController < ApplicationController
  
  layout 'admin'

  def menu
    #display text & links
  end

  def login
  end

  def attempt_login
    if params[:username].present? && params[:password].present?
      found_user = AdminUser.where(:username => params[:username])  #uses hash syntax that will sanitize the query
      if found_user
        authorized_user = found_user.authenticate(params)
      end
    end

    if authorized_user            #if logged in successfully
      session[:user_id] = authorized_user.id
      flash[:notice] = "You are now logged in."
      redirect_to(admin_path)     #goes to menu page
    
    else 
      flash.now[:noticce] = "Invalid username/password combination."
      render('login')
    end

  end

  def logout
    session[:user_id] = nil
    flash[:notice] = 'Logged out'
    redirect_to(access_login_path)
  end

end

app/helpers/access_helper.rb
module AccessHelper
end

app/views/access/login.html.erb
<%= @page_title = "Admin Login"%>

<div class="login">
    <%= form_tag(access_attempt_login_path, :method => :post ) do %>
    <table>
    <tr>
      <td><%=label_tag(:username)%></td>
      <td><%=text_field_tag(:username, params(:username))%></td>
    </tr>
    <tr>
      <td><%=label_tag(:password)%></td>
      <td><%=password_field_tag(:password)%></td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td><%=submit_tag("Log in")%></td>
    </tr>

app/views/access/menu.html.erb
<% @page_title = "Admin Menu"%>

<div class = "menu">
  <h2>Admin Menu</h2>
  <div class = "Identity" >Logged in as:</div>
  <ul>
    <li><%= link_to("Manage Subjects", subjects_path) %></li>
    <li><%= link_to("Manage Pages", pages_path) %></li>
    <li><%= link_to("Manage Sections", sections_path) %></li>
    <li><%= link_to("Manage Manage Admin Users", '#') %></li>
    <li><%= link_to("Manage Logout", access_logout_path) %></li>
  </ul>
</div>