config/routes.rb
Rails.application.routes.draw do

  root 'demo#index'

  get 'admin', :to => 'access#menu'   #if they are logged in, they'll get the menu page they wanted, else they get the login form.
  get 'access/menu'
  get 'access/login'    #can treat as resourceful route or simple controller

  post 'access/attempt_login'
  get 'access/logout'

  resources :posts
  resources :subjects do
    member do
      get :delete
    end
  end

  resources :pages do
    member do
      get :delete
    end
  end

  resources :sections do
    member do
      get :delete
    end
  end

  # get 'pages/index'
  # get 'pages/show'
  # get 'pages/new'
  # get 'pages/edit'
  # get 'pages/delete'
  
  # get 'subjects/index'
  # get 'subjects/show'
  # get 'subjects/new'
  # get 'subjects/edit'
  # get 'subjects/delete'
  # get 'self_contr/home'

  #root "demo#index"
  get 'demo/index'        #simple route
  #get 'demo/hello'  # get ':controller(/:action(/:id))'  #default route
  #get 'demo/about'
  #get 'demo/contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord

    belongs_to :subject, {:optional => false }
    has_and_belongs_to_many :admin_users

    scope :visible, lambda {where(:visible=>true)}
    scope :invisible, lambda {where(:visible=>false)}
    scope :sorted, lambda {order("position ASC")}
    scope :newest_first, lambda {where("created_at DESC")}
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/section.rb
class Section < ApplicationRecord
end

app/models/subject.rb
class Subject < ApplicationRecord

    has_many :pages
        
    scope :visible, lambda {where(:visible=>true)}
    scope :invisible, lambda {where(:visible=>false)}
    scope :sorted, lambda {order("position ASC")}
    scope :newest_first, lambda {where("created_at DESC")}

    validates_presence_of :name
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/access_controller.rb
class AccessController < ApplicationController
  
  layout 'admin'

  def menu
    #display text & links
  end

  def login
  end

  def attempt_login
    if params[:username].present? && params[:password].present?
      found_user = AdminUser.where(:username => params[:username])  #uses hash syntax that will sanitize the query
      if found_user
        authorized_user = found_user.authenticate(params)
      end
    end

    if authorized_user            #if logged in successfully
      session[:user_id] = authorized_user.id
      flash[:notice] = "You are now logged in."
      redirect_to(admin_path)     #goes to menu page
    
    else 
      flash.now[:noticce] = "Invalid username/password combination."
      render('login')
    end

  end

  def logout
    session[:user_id] = nil
    flash[:notice] = 'Logged out'
    redirect_to(access_login_path)
  end

end

app/controllers/demo_controller.rb
class DemoController < ApplicationController
  layout false
  def index
    #render('demo/index')  #these are default behaviour
  
    #render('demo/hello')

    @id = params['id'];
    @name = params[:name];
  end

  def hello
    #render('hello')       #these are default behaviour
    
    #redirect_to(controller: 'demo', action: 'index')
    #render('demo/index')


    #using instance vaiables
    @array = [1,2,3,4,5]
  end

  def about
    render('about_us')
  end

  def contact
  
    if ['us','ca'].include?(params[:country])
      @phone='+1 (987) 654-3210';
    elsif params[:country]='uk'
      @phone='(800) 555-6789';
    else
      @phone='(020) 7946 1234';
    end

    render('contact_us')
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  layout 'admin'

  before_action :find_subjects, :only => [:new, :create, :edit, :update]
  before_action :set_page_count, :only => [:edit, :update, :new, :create]

  def index
    @pages= Page.sorted
  end

  def show
    @page= Page.find(params[:id])
  end

  def new
    @page= Page.new
  
  
  end

  def create 
    @page= Page.new(page_params)
    if @page.save
      redirect_to(pages_path)
    else 

      
      render('new')
    end
  end

  def edit
    @page= Page.find(params[:id])
   
   
  end

  def update
    @page= Page.find(params[:id])
    if @page.update(page_params)
      redirect_to(page_path(@page))
   else 

    
      redirect_to('edit')
   end
  end

  def delete
    @page =Page.find(params[:id])
  end

  def destroy
    @page = Page.find(params[:id])
    @page.destroy
    redirect_to(pages_path)
  end

  private
  def page_params
    params.require(:page).permit(:name, :subject_id, :position, :visible, :permalink)
  end

  def find_subjects
      @subjects = Subject.sorted
  end

  def set_page_count
      @page_count = Page.count
    if params[:action] == 'new' || params[:action] == 'create'
        @page_action +=1
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :user_id, :views)
    end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  
    def index
      @sections= Section.sorted
    end
  
    def show
      @section= Section.find(params[:id])
    end
  
    def new
      @section= Section.new
    end
  
    def create 
      @section= Section.new(section_params)
      if @section.save
        redirect_to(sections_path)
      else 
        render('new')
      end
    end
  
    def edit
      @section= Section.find(params[:id])
    end
  
    def update
      @section= Section.find(params[:id])
      if @section.update(section_params)
        redirect_to(section_path(@section))
     else 
        redirect_to('edit')
     end
    end
  
    def delete
      @section= Section.find(params[:id])
    end
  
    def destroy
      @section= Section.find(params[:id])
      @section.destroy
      redirect_to(sections_path)
    end
  
    private
    def section_params
      params.require(:section).permit(:page_id, :name, :position, :visible, :content_type, :content)
    end
  
  end
  

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

    def error_messages_for(object)
        render(:partial =>'application/error_messages', :locals =>{:object =>object})
    end

    def status_tag(boolean, options={})
        options[:true_text] ||=''
        options[:false_text] ||=''

        if boolean
            content_tag(:span, options[:true_text], :class=>'status true')
        else
            content_tag(:span, options[:false_text], :class=>'status false')
        end
    end
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pages_n_helper.rb
module PagesNHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/self_contr_helper.rb
module SelfContrHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Simple CMS: <%= @page_title || "Admin area"%></title>
<%= stylesheet_link_tag('admin', :media =>'all')%>
    </head>
<body>

<div id="header">
    <h1>Simple CMS Admin</h1>
</div>

<div id='main'>
    <% if !flash[:notice].blank?%>
    <div class="notice">
    <% flash[:notice] %>
    </div>
    <% end %>

    <div id="content">
    <%= yield%>
    </div>

    <div id="footer">
        <p id="copyright">&copy; myfile.com</p>

</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleCms</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/_form.html.erb
<%= error_messages_for(f.object) %>

    <table summary="Pages form fields">
      <tr>
        <th>Name</th>
        <td><%= f.text_field(:name) %></td>
      </tr>
      <tr>
        <th>Subject ID</th>
        <td><%= f.select(:subject_id, @subjects.map {|s| [s.name, s.id]}) %></td>
      </tr>
      <tr>
        <th>Permalink</th>
        <td><%= f.text_field(:permalink) %></td>
      </tr>
      <tr>
        <th>Position</th>
        <td><%= f.select(:position, 1..@page_count) %></td>
      </tr>
        <tr>
        <th>Visible</th>
        <td><%= f.text_field(:visible) %></td>
      </tr>

    </table>

app/views/pages/delete.html.erb
<% if !flash[:notice].blank?%>
  <div class="notice">
  <% flash[:notice] %>
  </div>
  <% end %>

<%= link_to("<<Back to List", pages_path, :class => 'back-link')%>

<div class="pages delete">
<h2>Delete Page</h2>

<%= form_for(@page, :url =>page_path(@page), :method =>'delete') do |f| %>

<p>Are you sure you want to permanently delete this page?</p>

<p class="reference-name"><%=f.object.name %></p>

<div class="form-buttons">
    <%= f.submit("Delete Page") %>
</div>

<%end%>
</div>

app/views/pages/edit.html.erb
<%= link_to("<< Back to List", pages_path, :class => 'back-link-page') %>

<div class="Edit pages">
  <h2>Edit Pages</h2>

  <%= form_for(@page, :url =>page_path(@page), :method => 'patch') do |f| %>

    <table summary="Pages form fields">
      <tr>
        <th>Name</th>
        <td><%= f.text_field(:name) %></td>
      </tr>
      <tr>
        <th>Subject ID</th>
        <td><%= f.text_field(:subject_id) %></td>
      </tr>
      <tr>
        <th>Permalink</th>
        <td><%= f.text_field(:permalink) %></td>
      </tr>
      <tr>
        <th>Position</th>
        <td><%= f.text_field(:position) %></td>
      </tr>
        <tr>
        <th>Visible</th>
        <td><%= f.text_field(:visible) %></td>
      </tr>

    </table>

    <div class="form-buttons">
      <%= f.submit("Edit Page") %>
    </div>


  <% end %>
</div>

app/views/pages/index.html.erb
<div class="pages index">
  <h2>Pages</h2>

  <%= link_to("Add New Page", new_page_path, :class => 'action new') %>

  <table class="listing" summary="Pages list">
    <tr class="header">
      <th>#</th>
      <th>Subject ID</th>
      <th>Page</th>
      <th>Permalink</th>
      <th>Visible</th>
      <th>Sections</th>
      <th>Actions</th>
    </tr>
    <% @pages.each do |page| %>
    <tr>
      <td><%= page.position %></td>
      <td style="text-align:center;"><%= page.subject_id %></td>
      <td class="center"><%= page.name%></td>
      <td><%page.permalink%>
      <td class="center"><td><%= status_tag(page.visible)%></td>
            
      <td class="actions">
        <%= link_to("Show", page_path(page), :class=>'action show') %>    <!-- using resourceful routes -->
        <%= link_to("Edit", edit_page_path(page), :class => 'action edit') %>
        <%= link_to("Delete", delete_page_path(page), :class => 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/pages/new.html.erb
<%= link_to("<< Back to List", pages_path, :class => 'back-link-page') %>

<div class="pages new">
  <h2>Create Pages</h2>

  <%= form_for(@page, :url =>page_path(@page), :method => 'post') do |f| %>



    <div class="form-buttons">
      <%= f.submit("Create Page") %>
    </div>


  <% end %>
</div>

app/views/pages/show.html.erb
<%= link_to("<< Back to List", pages_path, :class => 'back-link') %>

<div class="pages show">
  <h2>Show Subject</h2>

  <table summary="Page detail view">
    <tr>
      <th>Name</th>
      <td><%= @page.name %></td>
    </tr>
    <tr>
      <th>Subject ID</th>
      <td><%= @page.subject_id %></td>
    </tr>
    <tr>
      <th>Permalink</th>
      <td><%= @page.permalink %></td>
    </tr>
      <th>Position</th>
      <td><%= @page.position %></td>
    </tr>
    
    <tr>
      <th>Visible?</th>
      <td><%= @page.visible ? 'true': 'false' %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @page.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @page.updated_at %></td>
    </tr>
  </table>

</div>