config/routes.rb
Rails.application.routes.draw do

  root 'demo#index'

  get 'admin', :to => 'access#menu'   #if they are logged in, they'll get the menu page they wanted, else they get the login form.
  get 'access/menu'
  get 'access/login'    #can treat as resourceful route or simple controller

  post 'access/attempt_login'
  get 'access/logout'

  resources :posts
  resources :subjects do
    member do
      get :delete
    end
  end

  resources :pages do
    member do
      get :delete
    end
  end

  resources :sections do
    member do
      get :delete
    end
  end

  # get 'pages/index'
  # get 'pages/show'
  # get 'pages/new'
  # get 'pages/edit'
  # get 'pages/delete'
  
  # get 'subjects/index'
  # get 'subjects/show'
  # get 'subjects/new'
  # get 'subjects/edit'
  # get 'subjects/delete'
  # get 'self_contr/home'

  #root "demo#index"
  get 'demo/index'        #simple route
  #get 'demo/hello'  # get ':controller(/:action(/:id))'  #default route
  #get 'demo/about'
  #get 'demo/contact'
end

app/models/subject.rb
class Subject < ApplicationRecord

    has_many :pages
        
    scope :visible, lambda {where(:visible=>true)}
    scope :invisible, lambda {where(:visible=>false)}
    scope :sorted, lambda {order("position ASC")}
    scope :newest_first, lambda {where("created_at DESC")}

    validates_presence_of :name
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
 
 layout 'admin'

  def index
    @subjects =Subject.order("position ASC")
    @page_title="All Subjects"
  end

  def show
    @subject = Subject.find(params[:id])
   
  end

  def new
    @subject= Subject.new({:name=>'Default'})
    @subject_count = Subject.count + 1
  end

  def create 
    #Instantiate a new subject using form parameters
    @subject = Subject.new(subject_params) 
    #params asking for subject that will return all the key value pairs in subject
    #Save the object
    if @subject.save
    #If save successful, redirect to the index action
      flash[:notice]= "Subject created successfully"
    redirect_to(subjects_path)

    #redirecting it to the index page
    else
    #If save fails, redisplay the form so user can fix problems
    @subject_count = Subject.count + 1
    #added because subject_count not initially passed.
    render('new') 
    #redirect it to the form
    #to data is saved in @subject is used to prepopulate the form
    end
  end

  def edit
    @subject=Subject.find(params[:id])
    @subject_count = Subject.count
  end

  def update
    @subject=Subject.find(params[:id]) 

    if @subject.update(subject_params)
      flash[:notice]= "Subject updated successfully"
      redirect_to(subject_path(@subject))
    else
      @subject_count = Subject.count
      render('edit')
    end
  end

  def delete
    @subject=Subject.find(params[:id])
  end

  def destroy
    @subject = Subject.find(params[:id])
    @subject.destroy
    flash[:notice]= "Subject '#{@subject.name}' destroyed successfully"
    redirect_to(subjects_path)
  end

  private
  def subject_params
    params.require(:subject).permit(:name, :position, :visible, :created_at)
  end

  #these are declared here seperately as we wouldn't have to redeclare the when needed again

end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<%= error_messages_for(f.object) %>

    <table summary="Subject form fields">
      <tr>
        <th>Name</th>
        <td><%= f.text_field(:name) %></td>
      </tr>
      <tr>
        <th>Position</th>
        <td><%= f.select(:position, 1..@subject_count) %></td>
      </tr>
      <tr>
        <th>Visible</th>
        <td><%= f.text_field(:visible) %></td>
      </tr>
      <tr>
        <th>Created</th>
        <td><%= f.datetime_select(:created_at, :order=> [:month, :day, :year]) %></td>
      </tr>
    </table>

app/views/subjects/delete.html.erb
<%= link_to("<<Back to List", subjects_path, :class => 'back-link')%>

<div class="subjects delete">
<h2>Delete Subject</h2>

<%= form_for(@subject, :url =>subject_path(@subject), :method =>'delete') do |f| %>

<p>Are you sure you want to permanently delete this subject?</p>

<p class="reference-name"><%=f.object.name %></p>

<div class="form-buttons">
    <%= f.submit("Delete Subject") %>
</div>

<%end%>
</div>

app/views/subjects/edit.html.erb
<%= link_to("<< Back to List", subjects_path, :class => 'back-link') %>

<div class="subjects edit">  <!--Changed-->
  <h2>Update Subject</h2>    <!--Changed-->

  <%= form_for(@subject, :url => subject_path(@subject), :method=>'patch') do |f| %>

    <%=render(:partial =>'form', :locals => {:f=>f})%>

    <div class="form-buttons">
      <%= f.submit("Update Subject") %> <!--Changed-->
    </div>

  <% end %>
</div>

app/views/subjects/index.html.erb
<div class="subjects index">
  <h2>Subjects</h2>

  <%= link_to("Add New Subject", new_subject_path, :class => 'action new') %>

  <table class="listing" summary="Subject list">
    <tr class="header">
      <th>#</th>
      <th>Subject</th>
      <th>Visible</th>
      <th>Pages</th>
      <th>Actions</th>
    </tr>
    <% @subjects.each do |subject| %>
    <tr>
      <td><%= subject.position %></td>
      <td><%= subject.name %></td>
      <!--<td class="center"><%= subject.visible ? 'Yes' : 'No' %></td>-->
      <td><%= status_tag(subject.visible)%>
      
      
      <td class="center"><%= subject.pages.size %></td>
      <td class="actions">
        
        <%= link_to("Show", subject_path(subject), :class=>'action show') %>    <!-- using resourceful routes -->
        <%= link_to("Edit", edit_subject_path(subject), :class => 'action edit') %>
        <%= link_to("Delete", delete_subject_path(subject), :class => 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/subjects/new.html.erb
<%= link_to("<< Back to List", subjects_path, :class => 'back-link') %>

<div class="subjects new">
  <h2>Create Subject</h2>

  <%= form_for(@subject, :url => subjects_path, :method => 'post') do |f| %>

<%=render(:partial =>'form', :locals => {:f=>f})%>

    <div class="form-buttons">
      <%= f.submit("Create Subject") %>
    </div>

  <% end %>
</div>

app/views/subjects/show.html.erb
<%= link_to("<< Back to List", subjects_path, :class => 'back-link') %>

<div class="subjects show">
  <h2>Show Subject</h2>

  <table summary="Subject detail view">
    <tr>
      <th>Name</th>
      <td><%= @subject.name %></td>
    </tr>
    <tr>
      <th>Position</th>
      <td><%= @subject.position %></td>
    </tr>
    <tr>
      <th>Visible?</th>
      <td><%= @subject.visible ? 'true' : 'false' %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @subject.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @subject.updated_at %></td>
    </tr>
  </table>

</div>